{"version":1,"defects":{"Tests\\Unit\\RouterTest::test_it_register_a_route":3,"Tests\\Unit\\RouterTest::testRegisterAPostRoute":3,"Tests\\Unit\\RouterTest::testNoRoutesRegistered":4,"Tests\\Unit\\RouterTest::testThrowsRouterNotFoundException with data set #2":3,"Tests\\Unit\\RouterTest::testThrowsRouterNotFoundException with data set #0":3,"Tests\\Unit\\RouterTest::testThrowsRouterNotFoundException with data set #4":3,"Error":4,"Tests\\Unit\\RouterTest::testResolveFromClosure":4,"Tests\\Services\\InvoiceServiceTest::testProcessInvoice":3,"Tests\\Services\\InvoiceServiceTest::testSendEmailWhileProcessing":3},"times":{"Tests\\Unit\\RouterTest::test_it_register_a_route":0.004,"Tests\\Unit\\RouterTest::testItRegisterARoute":0.003,"Tests\\Unit\\RouterTest::testRegisterARoute":0.003,"Tests\\Unit\\RouterTest::testRegisterAGetRoute":0,"Tests\\Unit\\RouterTest::testRegisterAPostRoute":0,"Tests\\Unit\\RouterTest::testNoRoutesRegistered":0,"Tests\\Unit\\RouterTest::testThrowsRouterNotFoundException with data set #0":0.001,"Tests\\Unit\\RouterTest::testThrowsRouterNotFoundException with data set #1":0,"Tests\\Unit\\RouterTest::testThrowsRouterNotFoundException with data set #2":0,"Tests\\Unit\\RouterTest::testThrowsRouterNotFoundException with data set #3":0,"Tests\\Unit\\RouterTest::testThrowsRouterNotFoundException with data set #4":0,"Error":0,"Tests\\Unit\\RouterTest::testResolveFromClosure":0,"Tests\\Unit\\RouterTest::testResolveRoute":0,"Tests\\Services\\InvoiceServiceTest::testProcessInvoice":0.014,"Tests\\Services\\InvoiceServiceTest::testSendEmailWhileProcessing":0.001,"Tests\\Services\\InvoiceServiceTest::testSendEmailWhenInvoiceIsProcessing":0.001}}